server:
  port: 8081

spring:
  application:
    name: football-tournament-app

  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method
    tags-sorter: method

app:
  security:
    jwt:
      token-validity-in-seconds: 3600
      jwt-secret: wJ8vP9yE+sN4aU6zR7bF0gK3jL5hV9mX8qZ1oP0dS7rB4eG2kI9fU3lO6yH8vA1nC5jT2bE4dR6sG8fI3kL7oA==