name: Java CI Build and Test (Maven)

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Step 3: Run Maven Verify (includes compile, test, package, integration-test)
      - name: Build, Test, and Verify with Maven
        run: mvn -B clean verify --file pom.xml

      # Step 4: Upload Test Reports (Optional but Recommended)
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ github.run_id }}
          path: |
            target/surefire-reports/
            target/failsafe-reports/
          retention-days: 7